/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import jakarta.persistence.EntityManager;
import jakarta.persistence.Query;
import jakarta.persistence.TypedQuery;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.Bicicleta;
import model.Cliente;
import model.Aluguel;
import service.AluguelService;
import service.ClienteService;
import service.UsuarioService;

/**
 *
 * @author Player14109423498
 */
public class TelaCalcular extends javax.swing.JFrame {

    private javax.swing.JTable jTable5;
    private javax.swing.JTextField txtTotalDiario1;
 
    /**
     * Creates new form TelaCalcular
     */
    public TelaCalcular() {
        initComponents();
        
        jTable5 = new javax.swing.JTable();
        JTextField txtTotalDiario = new javax.swing.JTextField();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblCalcularTotais1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtTotalDiario = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btnCalcular1 = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        lblTotalDiario = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCalcularTotais1.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        lblCalcularTotais1.setText("CALCULAR TOTAIS");
        jPanel2.add(lblCalcularTotais1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 240, -1));

        lblTotal.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        lblTotal.setText("TOTAL:");
        jPanel2.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        lblNome.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        lblNome.setText("Nome:");
        jPanel2.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtTotalDiario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(txtTotalDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 300, -1));

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 370, -1));

        btnCalcular1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btnCalcular1.setText("CALCULAR");
        btnCalcular1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalcular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 110, -1));

        btnEnviar.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btnEnviar.setText("ENVIAR");
        btnEnviar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 90, -1));

        txtTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 370, -1));

        lblTotalDiario.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        lblTotalDiario.setText("TOTAL DIÁRIO:");
        jPanel2.add(lblTotalDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 150, 30));

        btnVoltar.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel2.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular1ActionPerformed
       EntityManager em = null;
    try {
        // Cria uma instância do AluguelService para obter o EntityManager
        AluguelService aluguelService = new AluguelService();
        em = aluguelService.getEntityManager(); // Obtém o EntityManager

        // Consulta o valor total diário usando a view vw_total_aluguel_por_cliente
        String sql = "SELECT valor_total_diario FROM valor_total_aluguel"; 
        Query query = em.createNativeQuery(sql);

        // Executa a consulta e obtém a lista de resultados
        List<Double> resultados = query.getResultList();

               // Soma todos os valores totais diários
        Double totalDiario = 0.0;
        for (Double valor : resultados) {
            if (valor != null) {
                totalDiario += valor;
            }
        }

        // Exibe o total diário no campo txtTotalDiario1
        txtTotalDiario.setText(String.format("R$ %.2f", totalDiario));
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao calcular o total diário: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } finally {
        // Fecha o EntityManager
        if (em != null && em.isOpen()) {
            em.close();
        }
    }

    }//GEN-LAST:event_btnCalcular1ActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // Obtém o nome do cliente do campo de texto
        String nomeCliente = txtNome.getText().trim();

        // Verifica se o campo está vazio
        if (nomeCliente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o nome do cliente!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Busca o cliente pelo nome no banco de dados
        EntityManager em = null;
        try {
            AluguelService aluguelService = new AluguelService();
            em = aluguelService.getEntityManager(); // Método para obter o EntityManager

            String sql = "SELECT c.cliente_id FROM cliente c WHERE c.nome = :nome";
            Query query = em.createNativeQuery(sql);
            query.setParameter("nome", nomeCliente);
            Integer clienteId = (Integer) query.getSingleResult();

            // Calcula o total gasto pelo cliente
            double total = aluguelService.calcularTotalGastoPorCliente(clienteId);

            // Exibe o total no campo txtTotal
            txtTotal.setText(String.format("R$ %.2f", total));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar cliente ou calcular total: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (em != null) {
                em.close();
 }

  }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        new TelaAluguel().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalcular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular1;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCalcularTotais1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalDiario;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalDiario;
    // End of variables declaration//GEN-END:variables
}
