/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Bicicleta;
import model.Cliente;
import model.Aluguel;
import service.AluguelService;
import service.BicicletaService;
import service.ClienteService;

/**
 *
 * @author Player14109423498
 */
public class TelaAluguel extends javax.swing.JFrame {

    private AluguelService aluguelService;
    private DefaultTableModel tableModel;

    /**
     * Creates new form TelaAluguel
     */
    public TelaAluguel() {
        initComponents();
        aluguelService = new AluguelService();
        tableModel = (DefaultTableModel) jTable5.getModel();
        for (int i = 0; i < 5; i++) {
            tableModel.addRow(new Object[]{null, null, null, null, null, null});
        }
// Inicialização no construtor
        carregarAlugueis();

    }

    private void carregarAlugueis() {
        tableModel.setRowCount(0);
        List<Aluguel> alugueis = aluguelService.listarAlugueis(); // Obtém a lista de aluguéis
        for (Aluguel aluguel : alugueis) {
            tableModel.addRow(new Object[]{
                aluguel.getAluguel_id(),
                aluguel.getCliente().getCliente_id(), // Usa getCliente_id() em vez de getId()
                aluguel.getBicicleta().getBicicleta_id(), // Usa getBicicleta_id() em vez de getId()
                new SimpleDateFormat("HH:mm").format(aluguel.getHora_inicio()),
                new SimpleDateFormat("HH:mm").format(aluguel.getHora_termino()),
                aluguel.getPreco_hora()
            });
        }
        // Adiciona 5 linhas vazias para novos aluguéis
        for (int i = 0; i < 5; i++) {
            tableModel.addRow(new Object[]{null, null, null, null, null, null});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        btnCalcular4 = new javax.swing.JButton();
        btnAdicionar1 = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel5.setText("GERENCIAR ALUGUÉIS");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 280, -1));

        jScrollPane5.setPreferredSize(new java.awt.Dimension(580, 230));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "cliente_id", "bicicleta_id", "hora_inicio", "hora_termino", "preco_hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable5.setMinimumSize(new java.awt.Dimension(450, 120));
        jScrollPane5.setViewportView(jTable5);

        jPanel5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 580, 230));

        btnCalcular4.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btnCalcular4.setText("CALCULAR");
        btnCalcular4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalcular4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular4ActionPerformed(evt);
            }
        });
        jPanel5.add(btnCalcular4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 130, -1));

        btnAdicionar1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btnAdicionar1.setText("ADICIONAR");
        btnAdicionar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdicionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionar1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnAdicionar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 130, -1));

        btnExcluir.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel5.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 110, -1));

        btnVoltar.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel5.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcular4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular4ActionPerformed
        new TelaCalcular().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCalcular4ActionPerformed

    private void btnAdicionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionar1ActionPerformed
        // Declaração e inicialização dos serviços
        ClienteService clienteService = new ClienteService();
        BicicletaService bicicletaService = new BicicletaService();
        
        int selectedRow = jTable5.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha vazia para adicionar um aluguel.Deixe a coluna 'id' vazia!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verifica se a linha selecionada está vazia
        if (tableModel.getValueAt(selectedRow, 0) != null) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha vazia para adicionar um aluguel.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Coleta os dados da linha selecionada
        Integer clienteId = (Integer) tableModel.getValueAt(selectedRow, 1); // Coluna "cliente_id"
        Integer bicicletaId = (Integer) tableModel.getValueAt(selectedRow, 2); // Coluna "bicicleta_id"
        String horaInicio = (String) tableModel.getValueAt(selectedRow, 3); // Coluna "hora_inicio"
        String horaTermino = (String) tableModel.getValueAt(selectedRow, 4); // Coluna "hora_termino"
        Double precoHora = (Double) tableModel.getValueAt(selectedRow, 5); // Coluna "preco_hora"

        // Verifica se todos os campos foram preenchidos
        if (clienteId == null || bicicletaId == null || horaInicio == null || horaTermino == null || precoHora == null) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos da linha selecionada.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Cria um novo objeto Aluguel
            Aluguel aluguel = new Aluguel();

            // Busca o cliente no banco de dados
            Cliente cliente = clienteService.buscarClientePorId(clienteId);
            if (cliente == null) {
                JOptionPane.showMessageDialog(this, "Cliente não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            aluguel.setCliente(cliente);

            // Busca a bicicleta no banco de dados
            Bicicleta bicicleta = bicicletaService.buscarBicicletaPorId(bicicletaId);
            if (bicicleta == null) {
                JOptionPane.showMessageDialog(this, "Bicicleta não encontrada.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            aluguel.setBicicleta(bicicleta);

            // Converte as strings para Date
            SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm");
            Date horaInicioDate = formatoHora.parse(horaInicio);
            Date horaTerminoDate = formatoHora.parse(horaTermino);

            // Define os campos de data e hora
            aluguel.setHora_inicio(horaInicioDate);
            aluguel.setHora_termino(horaTerminoDate);

            // Define o preço por hora
            aluguel.setPreco_hora(precoHora);

            // Salva o aluguel no banco de dados
            aluguelService.salvarAluguel(aluguel);

            // Atualiza a tabela com os dados do banco de dados
            carregarAlugueis();

            JOptionPane.showMessageDialog(this, "Aluguel adicionado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de hora inválido. Use o formato HH:mm.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar aluguel: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnAdicionar1ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int selectedRow = jTable5.getSelectedRow(); // Usa jTable5 em vez de jTable3
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um aluguel para excluir.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int aluguelId = (int) tableModel.getValueAt(selectedRow, 0);
        int confirmacao = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja excluir o aluguel com ID " + aluguelId + "?",
                "Confirmar Exclusão",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacao == JOptionPane.YES_OPTION) {
            aluguelService.excluirAluguel(aluguelId);
            carregarAlugueis(); // Atualiza a tabela após a exclusão
            JOptionPane.showMessageDialog(this, "Aluguel excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed

        new TelaMenuPrincipal().setVisible(true);
        this.dispose();


    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAluguel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAluguel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAluguel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAluguel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAluguel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar1;
    private javax.swing.JButton btnCalcular4;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable5;
    // End of variables declaration//GEN-END:variables
}
